mplus = /home/mikewlcheung/bin/mplus

all: uni_fixed.out uni_rand1.out uni_rand2.out uni_mixed1.out uni_mixed2.out uni_miss.out uni_indices.out mul_fixed.out mul_rand1.out mul_rand2.out mul_mixed.out mul_med.out mul_mod.out 3l_rand1.out 3l_rand2.out 3l_mixed.out

%.out : %.inp
	$(mplus) $< 
